### PR TITLE
Add support for react.

### PR DESCRIPTION
**Pull request by jpstokes**
I've added support forReact project with files ending in "js" or "jsx".

### CODE REVIEW

**Comment by surdu** [comment]
By adding JS to the list of files, would't that expand a tag every time you press tab inside JS ? It's harmless in XML-like files, but for JS that might brake snippets that people use.

**Comment by jpstokes** [comment]
Went ahead and removed js extensions if users want to do use in js files they always have the option to add the js extention in plugins settings.

**Comment by surdu** [comment]
I don't think you intended to include in the PR the name and version change :)

I'm not an avid react user, but the .jsx is not essentially still a JS file ? As I said above, having this activated for file using JS syntax will disable all the snippets for JS.

Also, why the second animation in the description ?

**Comment by surdu** [comment]
It looks like you have this changes as a separate package. I assume you're not interested anymore in merging this into this package, so I will close this PR.

Feel free to reopen it at any time ;)

**Pull request closed without merging**
